module.exports = {
  MIN_NODE_VERSION: '8.9.4',
  OK: '✔',
  PACKAGES: [
    { name: 'lodash' },
    { name: 'react-native-app-link' },
    { name: 'react-native-dotenv' },
    { name: 'react-native-google-analytics-bridge' },
    { name: 'react-native-keyboard-spacer' },
    { name: 'react-native-modal' },
    { name: 'react-native-vector-icons' },
    { name: 'react-navigation-redux-helpers' },
    { name: 'react-navigation' },
    { name: 'react-redux' },
    { name: 'redux-api-middleware' },
    { name: 'redux-persist' },
    { name: 'redux-thunk' },
    { name: 'redux' },
    { name: 'urijs' },
  ],
};
